name: "Simple workflow"

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: "Echo hello world"
        run: echo "Hello world!"
      - name: "check node version"
        run: |
          node -v
          npm -v

  python-command:
    runs-on: ubuntu-18.04
    steps:
      - name: "run python command"
        run: "import sys; print(sys.version)"
        shell: python 
      